### ISSUE TITLE
Xdebug 3 support

### ISSUE THREAD

**Issue by Seldaek** [composer/xdebug-handler#114]
Xdebug 3 has an "off" switch so we can either set `XDEBUG_MODE=off` in env, or pass `-dxdebug.mode=off` to PHP when restarting. It should simplify things quite a bit as we don't need to rebuild the ini file and create a temp one etc.

**Comment by johnstevenson** [comment]
Great - this will certainly make things a lot easier. I'll have a play with the beta.

**Comment by Seldaek** [comment]
In addition to this, I just tried and can confirm that `xdebug.mode=off` in Xdebug3 indeed does not have any performance impact anymore. So we should make sure we do not restart if it's loaded but turned off.

**Comment by johnstevenson** [comment]
@Seldaek I wasn't entirely convinced by this from my initial research, so I'll have another go. Were you benchmarking against anything in particular (I think I used the bench script from the source)?

**Comment by Seldaek** [comment]
Benchmarked using `COMPOSER_DISABLE_NETWORK=1 composer update --dry-run --profile` vs `COMPOSER_ALLOW_XDEBUG=1 COMPOSER_DISABLE_NETWORK=1 composer update --dry-run --profile` on a relatively large project.

**Comment by Seldaek** [comment]
xdebug.mode is `develop` by default, in which I still saw a 20-30% performance impact (not terrible), running same benchmark with `php -dxdebug.mode=off` gave the same result as with the restarted one from xdebug-handler.

**Comment by ktomk** [comment]
So we can say that the xdebug handler as-is works for both xdebug.2 and xdebug.3, right?

One question then would be how to proceed with maintenance for this. Currently the strategy is to change ini values (also with the help of the environment).

From what I read from your findings @Seldaek (which are similar [but different] with mine, especially for the point after migrating to xdebug-3 that it is easy to control on CLI with the [`xdebug.mode`, and especially its new  `XDEBUG_MODE` environment parameter](https://xdebug.org/docs/all_settings#mode), one idea could be to differentiate based on xdebug version (2 or 3) and accommodate these changes with an additional strategy along the lines that it is keeping PHP configuration as is and only sets the `XDEBUG_MODE` environment variable to off.

Right now the `XDEBUG_MODE` environment parameter can not override xdebug-handler as xdebug-handler effectively prevents xdebug from being loaded (that is what it has been made for).

Which brings me to the idea that it is perhaps better to respect `XDEBUG_MODE` and support it within xdebug-handler.

Suggestion:

Given the `XDEBUG_MODE` environment parameter is set, then we should safely assume that this is the (more) guiding parameter over any `<prefix>_ALLOW_XDEBUG` and exit early with the consequence that xdebug-helper would not require to and does not restart.

This would also prevent to change the detailed part of the strategy _how_ PHP is restarted, nevertheless/but foremost I find this idea more fitting to the new xdebug.3 approach and make xdebug-helper well-integrated in general and also in specific with xdebug.3.

**Comment by Seldaek** [comment]
Good points about the env var. It does sound like a solid plan to me except for your bit about not changing the restart strategy. 

IMO we should use the var too when restarting to disable Xdebug 3, as it is a much simpler implementation and does not require touching the filesystem i see it as quite valuable.

**Comment by ktomk** [comment]
Yes, the suggestion above would benefit from additions, it covers the not restarting part, but it says nothing about what to do when restarting. So it does not show the whole picture.

Lets add up: Given xdebug.3, when the `XDEBUG_MODE` is not set, then ... .

A check that `xdebug.mode` is not "off" as this would also not require a restart.

For restarting, per ...

* ... standard settings: set `xdebug.mode=off` with php args
* ... persistent settings: set `XDEBUG_MODE=off` with environment.

No scanning / merging of the ini-files necessary. That was it already? - or am I missing something (next to the restoring of original values) ?

**Comment by Seldaek** [comment]
I think that's it yes 👍🏻

**Comment by johnstevenson** [comment]
> No scanning / merging of the ini-files necessary.

You would then miss any command line ini settings, so you still need to do the scanning and merging bit (and whilst you're doing that you might as well remove xdebug as well).

**Comment by ktomk** [comment]
@johnstevenson so we would miss the settings given on the command-line for PHP, right? And we can not assume it is non-configured per its args, true.

This does not break the first suggestion to adhere to XDEBUG_MODE when set first of all. This would already add Xdebug3 support.

For the second part (restart) it then would merely stay the same as-is (unless there is also a preference to support XDEBUG_MODE, thoughts?).

**Comment by Seldaek** [comment]
Hmm, could we not forward args from $_SERVER['argv'] to the restarted PHP? Instead of rewriting the INIs.

**Comment by ktomk** [comment]
@Seldaek No, not verbatim. PHP-CLI SAPI gives no option OOTB to access the command-line. It works if `/dev/proc/$PID/...` is available and re-parsing it (I have some code for this which I could contribute that's not too big but it is is not portable - it would help on my linux box thought).

**Comment by Seldaek** [comment]
Ah true this isn't part of the script's argv. Damn. 

We could possibly still avoid the writing of temp ini files if we detect that all the existing ini files satisfy the runtime ini config (thus proving there was no `-d` flag passed in to php). That'd make it a little cleaner as it then works read-only.

**Comment by johnstevenson** [comment]
I tried that when we did the full config merging stuff. The problem is that the runtime config includes all the default settings and the file config does not, so it is impossible to get a baseline.

**Comment by ktomk** [comment]
Well maybe it is: The PHP ini reading function allows to return as well incl. the default settings [`ini_get_all(..., $details)`](https://www.php.net/ini_get_all).

**Comment by johnstevenson** [comment]
Well I tried that and still couldn't get a reliable baseline. What is the big issue with creating a single ini file in the temp directory anyway?

**Comment by johnstevenson** [comment]
Okay, I agree that running with `xdebug.mode=off` has little impact on peformance, compared to not running Xdebug at all. Internally, the extension initialization does the normal ini and other init stuff then bails if the mode is off (rather than setting up various execution hooks) - so it is essentially inert.

Therefore it seems logical to not restart if the mode is off. However, implementing this would be a BC break (perhaps in behavior?) because `requiresRestart($isLoaded)` would need to change to `requiresRestart($default)`.

I've also got another optimization ready that bypasses the shell, by giving  `proc_open`  an array of restart arguments. In this case `restart($command)` would change to `restart(array $command)`.

So I guess we would need to bump to 2.0. Do you agree? @Seldaek

**Comment by Seldaek** [comment]
I really don't mind a bump to v2, so I'd say sure let's do that.

**Comment by ktomk** [comment]
I would bump the version number in any case (I personally do not think it is a BC break as the current behaviour on XDEBUG_MODE is _undefined_ which allows to change it backwardly) just so that users read the change-notes.

Please note that my suggestion was to make XDEBUG_MODE overriding. When set (not only to "off" but any non-empty value) to assume that xdebug is wanted in this configuration and therefore not restart. Requires a check for Xdebug 3.

This is a little different to your branch @johnstevenson that if I've seen it right is looking for "off" specifically.

There is a bit of wiggle-room how xdebug parses XDEBUG_MODE which is why I also thought about if set and non-empty, just consider the users best intention to use xdebug.

Setting XDEBUG_MODE to an empty string signals xdebug to use the `xdebug.mode` configuration setting.

Setting XDEBUG_MODE to commas only works like `off`.

**Comment by johnstevenson** [comment]
@Seldaek Cool.

@ktomk 
> Please note that my suggestion was to make XDEBUG_MODE overriding...

But the XDEBUG_MODE environment variable is another way of setting the mode in Xdebug. It has nothing to do with this library.

> There is a bit of wiggle-room how xdebug parses XDEBUG_MODE.

It looks like there will be a function to get the mode in Xdebug 3.1 (as per https://github.com/xdebug/xdebug/pull/733#issuecomment-803977514), so we will use that when it appears. Meanwhile my code is a best-attempt to determine its value:

```php
if (false !== ($mode = ini_get('xdebug.mode'))) {
    $this->mode = getenv('XDEBUG_MODE') ?: ($mode  ?: 'off');
}
```

> Setting XDEBUG_MODE to commas only works like off

That's because it parses as a comma-separated string and ends up with no values. I'm not sure if that would be considered correct (and my code misses this particular case), but who cares - we will restart and the process will take < 100ms longer.

**Comment by ktomk** [comment]
@johnstevenson was no critique of your code in the sense it would not parse, just FYI what I did found out when looking into parsing it (and then considered to not parse beyond empty or not).

> But the XDEBUG_MODE environment variable is another way of setting the mode in Xdebug. It has nothing to do with this library.

Wasn't XDEBUG_MODE introduced to be exactly what this library is aiming for but w/ a better OOTB experience? Using Xdebug 3 I would otherwise first have to learn about xdebug-handler and then that the tooling that incorporates it is making use of only to learn how the prefixed environment parameter is named to achieve the same (using xdebug).

I'd say it's one of the matters of xdebug 3 support for this library.

**Comment by johnstevenson** [comment]
I would have thought that XDEBUG_MODE was introduced as another way to set the mode in Xdebug. We shouldn't be second-guessing what a user's intentions are. More importantly, if xdebug-handler is being used then the intention is to remove Xdebug from the process - and there is already a way of overriding this.

**Comment by ktomk** [comment]
@johnstevenson Yes, only ignoring that it's used as a service in the utility (e.g. composer, rector etc.), which is different from _where_ it is used and _by whom_ (the user, that is on the computer where PHP is actually configured). So making XDEBUG_MODE override is not second guessing, that parameter there only is if the user configured it for her environment.

Think from a perspective of a user who wants to contribute to such a utility and needs step-debugging for it. When xdebug-handler was introduced you had to use the xdebug-handler environment parameter to enable step-debugging as this was xdebug2 that time which didn't have an environment parameter to control it on that level.

Since xdebug3 this has changed, only xdebug-handler is lacking support for that new xdebug parameter.

You can have it your way, it's in my eyes just bad usability (not more as-is thought) then and this would be having let the chance pass to improve it (which was not possible before xdebug3) and if I may add: without bringing anything to the table what didn't work the same before (regarding XDEBUG_MODE).

**Comment by johnstevenson** [comment]
Implemented in https://github.com/composer/xdebug-handler/pull/126
