### ISSUE TITLE
Cleanups now that proc_open is used

### ISSUE THREAD

**Issue by Seldaek** [composer/xdebug-handler#117]
I wonder.. is Process::supportsColor and the whole colorOption concept still needed? I am guessing this was all workarounds because STDOUT wasn't bound properly in the child process. Not urgent by any means, but it might be good to clean things up.

**Comment by johnstevenson** [comment]
Some Windows psuedo-terminals use named pipes as the underlying redirection method (cygwin, msys2) so `stream_isatty` returns false and fstat mode is `S_IFIFO` FIFO (rather than `S_IFCHR` character device) for all fds, regardless of passthru or proc_open. Plus there is the Hyper terminal which uses HTML/CSS. So I think the colorOption bit needs to stay.

One thing I might look at is not restarting through a shell, but invoking PHP directly, which can now be done on PHP 7.4+. We should also be able to handle Windows CTLR events on PHP 7.4+.

**Comment by Seldaek** [comment]
Alright. Not sure what you mean by invoking PHP directly but sounds good :)

**Comment by johnstevenson** [comment]
Prior to PHP 7.4, the execution functions use the native OS shell:

- passthru and friends use `popen` on Unix (which invokes the shell) and the Windows equivalent uses `cmd.exe /c "command"`.
- proc_open uses `execl("/bin/sh", "sh", "-c", command)` or CreateProcess with `cmd.exe /c command`

(except proc_open on Windows which allows the `bypass_shell` option).

However, PHP7.4 allows the `cmd` param for proc_open to be an array, which opens the process (ie. the first element of the array) directly - having quoted each argument in an OS specific way.

All I've got to remember is to add `php` as the first argument on Unix.

**Comment by Seldaek** [comment]
Ah I see, guess I missed that in the release notes. First arg should be PHP_BINARY then I assume regardless of platform? Not sure I get your last statement.

**Comment by johnstevenson** [comment]
> Not sure I get your last statement.

Thanks. Neither do I on re-reading it and the the code! (that bit was more of a note to me)

On nix, PHP extracts the process name from the cmd array, then runs `execvp(command, argv)`, where `command` is the process name and `argv` is the cmd array. I had incorrectly assumed that I needed to add the process name back in (for argv0) but on inspection PHP doesn't actually remove it.

**Comment by johnstevenson** [comment]
> Some Windows psuedo-terminals use named pipes as the underlying redirection method (cygwin, msys2) so stream_isatty returns false and fstat mode is S_IFIFO FIFO (rather than S_IFCHR character device) for all fds, regardless of passthru or proc_open. Plus there is the Hyper terminal which uses HTML/CSS. So I think the colorOption bit needs to stay.

Sorry, I must have been having a bad day as I've confused myself again here. While the above is true, an application determines whether the output stream supports color and they generally take care of the above. 

> I wonder.. is Process::supportsColor and the whole colorOption concept still needed? I am guessing this was all workarounds because STDOUT wasn't bound properly in the child process. 

So to correctly answer your original question: the color option stuff can be dispensed with if we only use `proc_open`, because by using it as we do (with an empty `descriptorspec` array) the original fds are used in the child process - unlike passthru and friends which create a pipe to stdout.
