### ISSUE TITLE
Make environment variable names configurable

### ISSUE THREAD

**Issue by alcohol** [composer/xdebug-handler#5]

**Comment by keradus** [comment]
if we want a package to be more widely used, having this issue solved is must-have. Either by configuration, either by overwritting (so start using LSB for constants)

**Comment by johnstevenson** [comment]
Have you seen the PR for it? It requires an appName to be passed in the constructor, which is then used to create the variables. Would this be suitable for your use case?

Sorry, but I don't understand what you mean by: "so start using LSB for constants"

**Comment by keradus** [comment]
Yes, I saw. And especially because of that, I gave my :+1: for issue, as solving the issue is IMHO must have, while there are multiple ways to solve it, and I leave decision on how to solve it to package manager (so I not commented PR).

[LSB](http://php.net/manual/pl/language.oop5.late-static-bindings.php) would change `self::FOO` into `static::FOO`, so instead of parametrizing the constructor one would be able to overwrite a constant in child class.

**Comment by johnstevenson** [comment]
Ah, late static binding -that is actually on my list to do. I'd personally prefer the constructor approach, but we'll come to a decision between us.

Currently if you supplied PHPCS you would obviously end up with `PHPCS_ALLOW_XDEBUG` and `PHPCS_ORIGINAL_INIS`. Is this what you would want, or something different?

**Comment by keradus** [comment]
that's why I said I don't want to affect which solution would be taken ;)

Sorry, I am not connected to PHPCS anyhow.

**Comment by johnstevenson** [comment]
Ah, Github made out you were the repo owner from your linked issue.

**Comment by keradus** [comment]
different tool.
PHP Coding Standards Fixer is not PHP Code Sniffer ;)

**Comment by johnstevenson** [comment]
Integrated in https://github.com/composer/xdebug-handler/commit/d9b57d593311239c581b461f4c6eec7a077edd24
